# navbar
menu:
  Home: /
  Archives: /archives/
  # Categories: /categories/
  Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  headerlink: "#"

# comments
comments:
  post: true
  about: false

# article directory sidebar
sidebar: true

# Analytics
## Baidu Analytics
baidu_analytics: Your baidu Analytics ID
## Google Analytics
google_analytics: Your Google Analytics ID

# Comments
## Duoshuo
duoshuo_shortname: gefangshuai
## Disqus
#disqus_shortname: gefangshuai

# Social links
social:
  email: gefangshuai@outlook.com
  # stack-overflow:
  # twitter:
  # facebook:
  github: https://github.com/gefangshuai
  # weibo: 
  # zhihu: 
  rss: /atom.xml